### ISSUE TITLE
layout.css & layout2.css

### ISSUE THREAD

**Issue by JanSilberg** [JanSilberg/bigbadvoododaddy#9]
Jeg kan se der er noget forskel på de 2 filer. - Er det meningen, at begge skal være en del af projektet, eller er en af dem bare en test? :)

**Gælder: layout.css & layout2.css**

**Comment by cath3161** [comment]
Den ene er bare en test, men ikke den rigtige som jeg ville have lagt op

**Comment by JanSilberg** [comment]
Efter aftale er de 2 filer blevet slettet, og issue er løst.
